export const ESELON_1_OPTIONS = [
  "Deputi Bidang Pengelolaan Sampah, Limbah, dan Bahan Berbahaya dan Beracun",
  "Inspektorat Utama",
  "Sekretariat Kementerian/Sekretariat Utama",
  "Deputi Bidang Penegakan Hukum Lingkungan Hidup",
  "Deputi Bidang Pengendalian Perubahan Iklim dan Tata Kelola Nilai Ekonomi Karbon",
  "Deputi Bidang Pengendalian Pencemaran dan Kerusakan Lingkungan",
  "Deputi Bidang Tata Lingkungan dan Sumber Daya Alam Berkelanjutan",
  "WCC",
] as const;

export const ESELON_2_OPTIONS = [
  "Direktorat Penanganan Sampah",
  "Inspektorat II",
  "Inspektorat I",
  "Direktorat Pengurangan Sampah dan Pengembangan Ekonomi Sirkular",
  "Pusat Pengendalian Lingkungan Hidup Sulawesi dan Maluku",
  "Direktorat Pengaduan dan Pengawasan Lingkungan Hidup",
  "Direktorat Pengelolaan Limbah Bahan Berbahaya Beracun dan Non Bahan Berbahaya Beracun",
  "Pusat Pengendalian Lingkungan Hidup Kalimantan",
  "Pusat Pengendalian Lingkungan Hidup Bali dan Nusa Tenggara",
  "Pusat Pengembangan Sumber Daya Manusia Lingkungan Hidup",
  "Biro Sumber Daya Manusia dan Organisasi",
  "Direktorat Adaptasi Perubahan Iklim",
  "Biro Perencanaan dan Keuangan",
  "Biro Umum",
  "Pusat Data dan Informasi",
  "Direktorart Perlindungan dan Pengelolaan Mutu Udara",
  "Direktorat Pengendalian Kebakaran Lahan",
  "Pusat Pengembangan Generasi Lingkungan Hidup",
  "Direktorat Perlindungan dan Pengelolaan Mutu Air",
  "Direktorat Sanksi Administratif Lingkungan Hidup",
  "Pusat Pengendalian Lingkungan Hidup Papua",
  "Direktorat Pengendalian Pencemaran dan Kerusakan Wilayah Pesisir dan Laut",
  "Direktorat Mitigasi Perubahan Iklim",
  "Direktorat Pengelolaan Bahan Berbahaya dan Beracun",
  "Pusat Sarana Pengendalian Lingkungan Hidup",
  "Pusat Pengendalian Lingkungan Hidup Jawa",
  "Direktorat Perlindungan dan Pengelolaan Ekosistem Gambut",
  "Direktorat Perlindungan dan Pengelolaan Ekosistem Perairan Darat",
  "Pusat Pengendalian Lingkungan Hidup Sumatera",
  "Direktorat Pencegahan Dampak Lingkungan Kebijakan Wilayah dan Sektor",
  "Direktorat Penyelenggaraan Sumber Daya Alam Berkelanjutan",
  "Direktorat Tata Kelola Penerapan Nilai Ekonomi Karbon",
  "Direktorat Mobilisasi Sumber Daya Pengendalian Perubahan Iklim",
  "Direktorat Penegakan Hukum Pidana Lingkungan Hidup",
  "Direktorat Pemulihan Lahan Terkontaminasi dan Tanggap Darura Limbah Bahan Berbahaya Beracun dan Non Bahan Berbahaya Beracun",
  "Direkotrat Inventarisasi Gas Rumah Kaca dan Monitoring, Pelaporan dan Verifikasi",
  "Direktorat Penyelesaian Sengketa Lingkungan Hidup",
  "Biro Hukum dan Kerja Sama",
  "Biro Hubungan Masyarakat",
  "Direktorat Pencegahan Dampak Lingkungan Usaha dan Kegiatan",
  "Direktorat Pengendalian Kerusakan Lahan",
  "Direktorat Konservasi Keanekaragaman Hayati",
  "Pusat Standarisasi Instrumen Lingkungan Hidup",
  "WCC",
] as const;

export type SocialAccountEselon1 = (typeof ESELON_1_OPTIONS)[number];
export type SocialAccountEselon2 = (typeof ESELON_2_OPTIONS)[number];
